wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1644591717
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 15
      4: 3.10.2
      5: 0.12.10
      8:
      - 3
      - 5
