wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1659965395
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 15
      4: 3.9.7
      5: 0.12.21
      8:
      - 3
      - 5
